package dk.dtu.scout.generator;

import dk.dtu.scout.State;
import dk.dtu.scout.datatypes.StateKeys;
import dk.dtu.scout.dto.EvaluatedSolution;
import dk.dtu.scout.dto.Parameter;
import dk.dtu.scout.util.FormulaEvaluator;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
import java.util.Random;

import static dk.dtu.scout.generator.ReinforcementMode.ALL;
import static dk.dtu.scout.generator.ReinforcementMode.BEST_SO_FAR;
import static dk.dtu.scout.generator.ReinforcementMode.ITERATION_BEST;

/**
 * ACO generator for bitstring search spaces.
 * The generator maintains one pheromone value for each bit position. A new
 * bitstring is generated by sampling each bit independently according to its
 * The pheromone values are bounded between a configurable minimum and maximum
 * value. These bounds can be provided either as numbers or as formulas using
 * the problem dimension, for example "1/n" and "1 - 1/n".
 * @author s230632
 */
@Component
@Scope("prototype")
public class BitstringAcoGenerator implements Generator<boolean[]> {

    private double evaporationRate = 0.1;
    private double reinforcementRate = 0.1;

    private Object minPheromone = "1/n";
    private Object maxPheromone = "1 - 1/n";

    private ReinforcementMode reinforcementMode = BEST_SO_FAR;
    private boolean acceptEqualFitness = true;

    private double[] pheromoneVector;
    private State state;
    private EvaluatedSolution<boolean[]> bestSoFar;

    @Override
    public void init(State state) {
        this.state = state;
    }

    @Override
    public String id() {
        return "bitstring-aco";
    }

    @Override
    public String displayName() {
        return "Bitstring ACO Generator";
    }

    @Override
    public String description() {
        return "ACO generator for bitstrings using bounded position pheromones";
    }

    @Override
    public List<Parameter> params() {
        return List.of(
            new Parameter("evaporationRate", "Pheromone Evaporation Rate", "double", evaporationRate, 0.0, 1.0, null),
            new Parameter("reinforcementRate", "Pheromone Reinforcement Rate", "double", reinforcementRate, 0.0, 1.0, null),
            new Parameter("minPheromone", "Minimum Pheromone", "string", minPheromone, null, null, null),
            new Parameter("maxPheromone", "Maximum Pheromone", "string", maxPheromone, null, null, null),
            new Parameter("reinforcementMode", "Reinforcement Mode", "enum", reinforcementMode.name(), null, null, List.of("BEST_SO_FAR", "ITERATION_BEST", "ALL")),
            new Parameter("acceptEqualFitness", "Accept Equal Fitness", "boolean", acceptEqualFitness, null, null, null)
        );
    }

    @Override
    public void configure(Map<String, Object> params) {
        if (params.containsKey("evaporationRate")) {
            evaporationRate = resolveRate(params.get("evaporationRate"), "Pheromone evaporation rate");
        }

        if (params.containsKey("reinforcementRate")) {
            reinforcementRate = resolveRate(params.get("reinforcementRate"), "Pheromone reinforcement rate");
        }

        if (params.containsKey("minPheromone")) {
            minPheromone = params.get("minPheromone");
        }

        if (params.containsKey("maxPheromone")) {
            maxPheromone = params.get("maxPheromone");
        }

        boolean hasReinforcementMode = params.containsKey("reinforcementMode");

        if (hasReinforcementMode) {
            reinforcementMode = parseReinforcementMode(params.get("reinforcementMode"));
        }

        if (params.containsKey("acceptEqualFitness")) {
            acceptEqualFitness = (Boolean) params.get("acceptEqualFitness");
        }
    }

    @Override
    public List<String> supportedSearchSpaces() {
        return List.of("bitstring");
    }
    /**
     * Generates a new bitstring by sampling each bit according to the current
     * pheromone value at that position.
     * @param rng random number generator used for sampling bits
     * @return generated bitstring solution
     */
    @Override
    public boolean[] generate(Random rng) {
        if (pheromoneVector == null) {
            initializePheromones();
        }

        boolean[] result = new boolean[pheromoneVector.length];

        for (int i = 0; i < pheromoneVector.length; i++) {
            result[i] = rng.nextDouble() < pheromoneVector[i];
        }

        return result;
    }
    /**
     * Updates the pheromone vector using the latest evaluated generation and
     * publishes the current pheromone vector to the shared state.
     * @param state current run state containing the evaluated generation
     * @return state variables published by this generator
     */
    @Override
    public Map<String, Object> getStateVariables(State state) {
        if (pheromoneVector == null) {
            initializePheromones();
        }

        updatePheromones(state);
        state.update(Map.of(StateKeys.PHEROMONE_VECTOR, pheromoneVector));

        return Map.of(StateKeys.PHEROMONE_VECTOR, pheromoneVector);
    }
    /**
     * Initializes the pheromone vector with the initial pheromone value, which is
     * clamped between the resolved minimum and maximum pheromone bounds.
     * The initialized pheromone vector is published to the shared state.
     */
    private void initializePheromones() {
        int dimension = resolveDimension();
        PheromoneBounds bounds = resolvePheromoneBounds();
        double initialPheromone = clamp(0.5, bounds);

        pheromoneVector = new double[dimension];

        for (int i = 0; i < dimension; i++) {
            pheromoneVector[i] = initialPheromone;
        }

        state.update(Map.of(StateKeys.PHEROMONE_VECTOR, pheromoneVector));
    }
    /**
     * Updates the pheromone vector according to the selected reinforcement mode.
     * BEST_SO_FAR reinforces the best solution found so far.
     * ITERATION_BEST reinforces the best solution from the current generation.
     * ALL reinforces all solutions from the current generation with scaled weight.
     * @param state current run state containing StateKeys.GENERATION_EVALUATED
     */

    private void updatePheromones(State state) {
        Object evaluatedObj = state.get(StateKeys.GENERATION_EVALUATED);

        if (!(evaluatedObj instanceof List<?> evaluated) || evaluated.isEmpty()) {
            return;
        }

        switch (reinforcementMode) {
            case BEST_SO_FAR -> reinforceBestSoFar(evaluated);
            case ITERATION_BEST -> reinforceIterationBest(evaluated);
            case ALL -> reinforceAll(evaluated);
        }

        clampPheromones();
    }

    /**
     * Reinforces the best solution found so far by applying pheromone updates to its bits.
     * @param evaluated list of evaluated solutions from the current generation, used to update the best-so-far solution if necessary.
     */
    private void reinforceBestSoFar(List<?> evaluated) {
        updateBestSoFar(evaluated);
        evaporate();
        applyReinforcement(bestSoFar.value(), reinforcementRate);
    }
    /**
     * Reinforces the best solution from the current generation by applying pheromone updates to its bits.
     * @param evaluated list of evaluated solutions from the current generation, used to identify the iteration-best solution.
     */
    private void reinforceIterationBest(List<?> evaluated) {
        EvaluatedSolution<boolean[]> generationBest = bestOf(evaluated);
        evaporate();
        applyReinforcement(generationBest.value(), reinforcementRate);
    }
    /**
     * Reinforces all solutions from the current generation by applying pheromone updates to their bits.
     * The reinforcement rate is scaled by the number of evaluated solutions to prevent excessive pheromone increases.
     * @param evaluated list of evaluated solutions from the current generation, used to identify the solutions to reinforce.
     */
    @SuppressWarnings("unchecked")
    private void reinforceAll(List<?> evaluated) {
        evaporate();

        double scaledRate = reinforcementRate / evaluated.size();

        for (Object entry : evaluated) {
            EvaluatedSolution<boolean[]> solution = (EvaluatedSolution<boolean[]>) entry;
            applyReinforcement(solution.value(), scaledRate);
        }
    }
    /**
     * Updates the best-so-far solution if the best solution from the current generation is better (or equal if configured) than the existing best-so-far.
     * @param evaluated list of evaluated solutions from the current generation, used to identify the generation-best solution for comparison.
     */
    private void updateBestSoFar(List<?> evaluated) {
        EvaluatedSolution<boolean[]> generationBest = bestOf(evaluated);
        if (bestSoFar == null || isAcceptedAsBestSoFar(generationBest)) {
            bestSoFar = new EvaluatedSolution<>(generationBest.value().clone(), generationBest.fitness());
        }
    }

    private boolean isAcceptedAsBestSoFar(EvaluatedSolution<boolean[]> candidate) {
        return acceptEqualFitness ? candidate.fitness() >= bestSoFar.fitness() : candidate.fitness() > bestSoFar.fitness();
    }
    /**
     * Applies pheromone reinforcement to the bits of a given solution by increasing the pheromone values at positions where the solution has a true bit.
     * @param reinforcedSolution the solution whose bits are used to determine which pheromone values to reinforce
     * @param rate the amount by which to increase the pheromone values for the reinforced bits
     */
    private void applyReinforcement(boolean[] reinforcedSolution, double rate) {
        for (int i = 0; i < pheromoneVector.length; i++) {
            if (reinforcedSolution[i]) {
                pheromoneVector[i] += rate;
            }
        }
    }
    /**
     * Applies evaporation to the pheromone vector by reducing all pheromone values according to the configured evaporation rate.
     * This method is called before applying reinforcement to ensure that pheromone values do not grow indefinitely.
     */
    private void evaporate() {
        for (int i = 0; i < pheromoneVector.length; i++) {
            pheromoneVector[i] *= (1.0 - evaporationRate);
        }
    }
    /**
     * Identifies the best solution from a list of evaluated solutions by comparing their fitness values.
     * @param evaluated list of evaluated solutions from which to identify the best solution
     * @return the evaluated solution with the highest fitness value
     */
    @SuppressWarnings("unchecked")
    private EvaluatedSolution<boolean[]> bestOf(List<?> evaluated) {
        EvaluatedSolution<boolean[]> best = null;

        for (Object entry : evaluated) {
            EvaluatedSolution<boolean[]> candidate = (EvaluatedSolution<boolean[]>) entry;

            if (best == null || candidate.fitness() > best.fitness()) {
                best = candidate;
            }
        }

        return best;
    }

    /**
     * Resolves a parameter value that is expected to represent a rate (such as evaporation or reinforcement rate) to a double between 0 and 1.
     * @param value the parameter value to resolve, which can be a number or a formula string that evaluates to a number
     * @param label a human-readable label for the parameter, used in error messages if the value is invalid
     * @return the resolved rate as a double between 0 and 1
     */
    private double resolveRate(Object value, String label) {
        double resolved = ((Number) value).doubleValue();

        if (resolved < 0.0 || resolved > 1.0) {
            throw new IllegalArgumentException(label + " must be between 0 and 1");
        }

        return resolved;
    }

    private int resolveDimension() {
        return ((Number) state.get(StateKeys.DIMENSION)).intValue();
    }
    /**
     * Resolves the minimum and maximum pheromone bounds from the configured parameter values, which can be either numbers or formula strings.
     * The resolved bounds are validated to ensure they are between 0 and 1 and that the minimum is not greater than the maximum.
     * @return a PheromoneBounds record containing the resolved minimum and maximum pheromone values
     */
    private PheromoneBounds resolvePheromoneBounds() {
        int dimension = resolveDimension();

        double resolvedMin = resolveFormulaOrNumber(minPheromone, dimension, "Minimum pheromone");
        double resolvedMax = resolveFormulaOrNumber(maxPheromone, dimension, "Maximum pheromone");

        validatePheromoneBounds(resolvedMin, resolvedMax);

        return new PheromoneBounds(resolvedMin, resolvedMax);
    }
    /**
     * Resolves a parameter value that can be either a number or a formula string that evaluates to a number.
     * @param value the parameter value to resolve
     * @param dimension the problem dimension to use when evaluating formula strings
     * @param label a human-readable label for the parameter, used in error messages if the value is invalid
     * @return the resolved numeric value as a double
     */
    private double resolveFormulaOrNumber(Object value, int dimension, String label) {
        double resolved = switch (value) {
            case String formula -> FormulaEvaluator.eval(formula, dimension);
            case Number number -> number.doubleValue();
            default -> throw new IllegalArgumentException(label + " must be a number or formula");
        };

        if (!Double.isFinite(resolved)) {
            throw new IllegalArgumentException(label + " must resolve to a finite number");
        }

        return resolved;
    }

    private void validatePheromoneBounds(double min, double max) {
        if (min < 0.0 || min > 1.0) {
            throw new IllegalArgumentException("Minimum pheromone must be between 0 and 1");
        }

        if (max < 0.0 || max > 1.0) {
            throw new IllegalArgumentException("Maximum pheromone must be between 0 and 1");
        }

        if (min > max) {
            throw new IllegalArgumentException("Minimum pheromone cannot be greater than maximum pheromone");
        }
    }

    private void clampPheromones() {
        PheromoneBounds bounds = resolvePheromoneBounds();

        for (int i = 0; i < pheromoneVector.length; i++) {
            pheromoneVector[i] = clamp(pheromoneVector[i], bounds);
        }
    }

    private double clamp(double value, PheromoneBounds bounds) {
        return Math.max(bounds.min(), Math.min(bounds.max(), value));
    }

    private ReinforcementMode parseReinforcementMode(Object value) {
        String normalized = value.toString().trim().toUpperCase();

        try {
            return ReinforcementMode.valueOf(normalized);
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("Invalid reinforcement mode: " + value, ex);
        }
    }

    private record PheromoneBounds(double min, double max) {
    }
}