# Executor pool settings
scout.executors.request.core-pool-size=4
scout.executors.request.max-pool-size=16
scout.executors.request.queue-capacity=200
scout.executors.request.await-termination-seconds=30

scout.executors.run.core-pool-size=4
scout.executors.run.max-pool-size=16
scout.executors.run.queue-capacity=1000
scout.executors.run.await-termination-seconds=60

run.status.maxEntries=500
